@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InternTrackerParser" as InternTrackerParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant ":AddCommand" as AddCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("add n/Jane...")
activate LogicManager

LogicManager -> InternTrackerParser : parseCommand("add n/Jane...")
activate InternTrackerParser

create AddCommandParser
InternTrackerParser -> AddCommandParser : new AddCommandParser()
activate AddCommandParser

AddCommandParser --> InternTrackerParser
deactivate AddCommandParser

InternTrackerParser -> AddCommandParser : parse("n/Jane...")
activate AddCommandParser

create AddCommand
AddCommandParser -> AddCommand
activate AddCommand

AddCommand --> AddCommandParser :
deactivate AddCommand

AddCommandParser --> InternTrackerParser :
deactivate AddCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommandParser -[hidden]-> InternTrackerParser
destroy AddCommandParser

InternTrackerParser --> LogicManager : AddCommand
deactivate InternTrackerParser

LogicManager -> AddCommand : execute()
activate AddCommand

AddCommand -> Model : addInternApplication()
activate Model

Model --> AddCommand
deactivate Model

create CommandResult
AddCommand -> CommandResult
activate CommandResult

CommandResult --> AddCommand
deactivate CommandResult

AddCommand --> LogicManager : result
deactivate AddCommand
AddCommand -[hidden]-> LogicManager
destroy AddCommand

[<--LogicManager
deactivate LogicManager
@enduml
