@startuml
skin rose
skinparam ActivityFontSize 10
skinparam ArrowFontSize 10
skinparam activityDiamondFontSize 50

start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command commits
intern applications])
    :Save internship applications
to saved states and perform
action;
else ([else])
:Check if command is undo;
if () then ([command is undo])
    :Check if there are saved states;
if () then ([there are saved states)
    :perform undo;
else ([else])
    : show already at latest change;
endif
else ([else])
endif
endif
stop
@enduml
