@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyInternTracker" as ReadOnlyInternTracker
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class InternTracker
Class ModelManager
Class UserPrefs

Class UniqueApplicationList
Class InternApplication
Class Status
Class Cycle
Class Company
Class Role
Class Deadline
Class Note

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

InternTracker .up.|> ReadOnlyInternTracker

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyInternTracker
ModelManager -left-> "1" InternTracker
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

InternTracker *--> "1" UniqueApplicationList
UniqueApplicationList --> "~* all" InternApplication
InternApplication *--> Company
InternApplication *--> Role
InternApplication *--> Cycle
InternApplication *--> Status
InternApplication *--> Deadline
InternApplication *--> "*" Note

InternApplication -[hidden]up--> I
UniqueApplicationList -[hidden]right-> I

Company -[hidden]right-> Role
Role -[hidden]right-> Cycle
Cycle -[hidden]right-> Status

ModelManager --> "~* filteredSorted" InternApplication
@enduml
