@startuml
!include style.puml
skinparam ArrowFontStyle plain

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR

user -[USER_COLOR]> ui : "click on card number 1"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("view 1")
activate logic LOGIC_COLOR

logic --[LOGIC_COLOR]> ui : CommandResult
deactivate logic

ui--[UI_COLOR]> ui : displayDetails(details)
activate ui UI_COLOR

ui --[LOGIC_COLOR]> ui
deactivate ui

ui--[UI_COLOR]> user : details displayed to user
deactivate ui
@enduml
