@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InternTrackerParser" as InternTrackerParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedInternTracker" as VersionedInternTracker MODEL_COLOR
end box
[-> LogicManager : execute("undo")
activate LogicManager

LogicManager -> InternTrackerParser : parseCommand("undo")
activate InternTrackerParser

create UndoCommand
InternTrackerParser -> UndoCommand
activate UndoCommand

UndoCommand --> InternTrackerParser
deactivate UndoCommand

InternTrackerParser --> LogicManager : u
deactivate InternTrackerParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoAction()
activate Model

Model -> VersionedInternTracker : undo()
activate VersionedInternTracker

VersionedInternTracker --> Model :
deactivate VersionedInternTracker

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
